version: '3.7'

services:
  fast_api:
    build: ./fast api
    restart: always
    # env_file:
      # - ./django/.env
        #  volumes:
            #  - static:/static
    ports:
      - 8000:8000
    depends_on:
      - mysqldb
    links:
      - mysqldb
        # command: ['python', 'project/manage.py', 'runserver','0.0.0.0:8000']
  mysqldb:
    image: mysql
    restart: always
    # volumes:
      # - ./mysql/scripts:/docker-entrypoint-initdb.d
      # - /Users/amin/Documents/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=family"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - fast_api
volumes:
  static:
  mysql_data:
